# Generated by Django 4.0.2 on 2022-03-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nom de la catégorie', max_length=200, verbose_name='Nom du Catégorie')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du video', max_length=200, verbose_name='Titre')),
                ('author', models.CharField(help_text='Autheur du video', max_length=200, verbose_name='Auteur')),
                ('description', models.TextField(help_text='Description pour le video', max_length=2000, verbose_name='Description')),
                ('video_url', models.CharField(help_text='Url du video ', max_length=200, verbose_name='Video URL')),
                ('thumbnail_url', models.CharField(help_text='Url du thumbnail (gif)', max_length=200, verbose_name='Thumbnail URL')),
                ('date', models.DateField()),
                ('tags', models.CharField(help_text='Tags du video (séparés par des virgules)', max_length=200)),
                ('category_name', models.ForeignKey(help_text='choisi la catégorie du video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='epheme_app.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['title', '-date'],
            },
        ),
    ]
