# Generated by Django 4.0.3 on 2022-03-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epheme_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Youtube ou Vimeo', max_length=200, verbose_name='Nom du site')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='source_name',
            field=models.ForeignKey(help_text='Youtube ou Vimeo', null=True, on_delete=django.db.models.deletion.CASCADE, to='epheme_app.source', verbose_name='Source'),
        ),
    ]
