# Generated by Django 4.0.3 on 2022-03-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iepheme_app', '0002_source_video_source_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
    ]
