# Generated by Django 4.0.3 on 2022-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iepheme_app', '0004_alter_category_options_category_alphabetic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='OwO', help_text='Description pour la catégorie', max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
