# Generated by Django 4.0.3 on 2022-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iepheme_app', '0005_category_description_video_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=' ', help_text='Description pour la catégorie', max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
