# Generated by Django 4.0.3 on 2022-04-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iepheme_app', '0007_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
