# Generated by Django 4.0.3 on 2022-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iepheme_app', '0008_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=' ', help_text='Description pour la catégorie', max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
